name: C/C++ CI for iOS

on:
  push:
    branches:
    - master
    - release/*
    - buildme/*
  pull_request:
    branches:
    - master
  schedule:
  - cron: 0 2 * * 1-5

jobs:
  build:
    runs-on: macOS-latest
    strategy:
        matrix:
            config: [release, debug]
            simulator: ["'iPhone 8'", "'iPad Air (3rd generation)'"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
      continue-on-error: true
    - name: build
      run: ./build-tests-ios.sh ${{ matrix.config }} ${{ matrix.simulator }}
